#ifndef _HONEYWELL_SAMPLING_DATA
#define _HONEYWELL_SAMPLING_DATA

#include "datatype.h"


#define HONEYWELL_RATE			11185   //斜率
//#define HONEYWELL_RATE			9000
//#define PRESSURE_SAFETY_THRESHOLD_LOW_LIMIT   0x90
//#define	PRESSURE_SAFETY_THRESHOLD_HIGH_LIMIT	0xC0
//#define PRESSURE_SAFETY_THRESHOLD 160   //0xA0表示10.0，对应十进制160

#define PRESSURE_SAFETY_THRESHOLD_LOW_LIMIT   18
#define	PRESSURE_SAFETY_THRESHOLD_HIGH_LIMIT	22
#define PRESSURE_SAFETY_THRESHOLD 20
//y=ax+b
#define PRESSURE_SENSOR_VALUE(x) ((uint32_t)(((HONEYWELL_RATE)*(x))+HONEYWELL_ZERO_POINT))

#define HONEYWELL_SAMPLING_DATA_PERIOD 5

typedef enum 
{
	HONEYWELL_START,
	HONEYWELL_NONE,
//	HONEYWELL_WAIT_5ms,
	HONEYWELL_READ_DATA,
	HONEYWELL_SAMPLE_DATA_FINISH
}HONEYWELL_STATE;

void honeywell_sampling_data(void);
UINT32 trans_xmmHg_2_adc_value(UINT8 xmmHg);
#endif //_HONEYWELL_SAMPLING_DATA


